services:
  mysql:
    image: mysql:8.0
    container_name: demo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: banking_service
      MYSQL_USER: root
      MYSQL_PASSWORD: bankingpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    image: jainish545/banking-service:latest
    container_name: demo_banking_service
    restart: always
    depends_on:
      - mysql
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://root:admin123@mysql:3306/banking_service
      NODE_ENV: demo
      PORT: 4000

volumes:
  mysql_data:
