-- AlterTable
ALTER TABLE `account` ADD COLUMN `AccountType` ENUM('SAVINGS', 'CHECKING', 'CREDIT', 'LOAN') NOT NULL DEFAULT 'SAVINGS',
    ADD COLUMN `closedAt` DATETIME(3) NULL,
    ADD COLUMN `isPrimary` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `status` ENUM('ACTIVE', 'INACTIVE', 'CLOSED', 'FROZEN') NOT NULL DEFAULT 'ACTIVE';
