name: Build and Push Docker Image

on:
  push:
    branches: 
      - feat/ci-cd-docker
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t jainish545/banking-service:latest .

      - name: Push Docker image
        run: docker push jainish545/banking-service:latest
